### ISSUE TITLE
Dep / With

### ISSUE THREAD

**Issue by RogerHuba** [TW2002/mombot#20]
Add help for k and m for shortcuts

**Comment by DMC73120** [comment]
I also use the m shortcut for wsst

**Comment by daynez** [comment]
The keep command creates its own help file already.

setVar $BOT~help[1] $BOT~tab&"keep {amount} "
setVar $BOT~help[2] $BOT~tab&"   Will withdraw or deposit to/from citadel so you"
setVar $BOT~help[3] $BOT~tab&"   have the amount of credits requested."
setVar $BOT~help[4] $BOT~tab&"     "
setVar $BOT~help[5] $BOT~tab&"   Examples:"
setVar $BOT~help[6] $BOT~tab&"      >keep 500k"
setVar $BOT~help[7] $BOT~tab&"      >keep 2m"
setVar $BOT~help[8] $BOT~tab&"      >keep 200000"
setVar $BOT~help[8] $BOT~tab&"     "
setVar $BOT~help[8] $BOT~tab&"                     - Author: Deign "
gosub :bot~helpfile

**Comment by RogerHuba** [comment]
Wal already incorporated in some versions of the commands but not all.  Will unify.

**Comment by RogerHuba** [comment]
Done
