### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by RogerHuba** [TW2002/mombot#27]
Attempted to run

'update figs limps armids cim warps'

Only updated cim.

**Comment by RogerHuba** [comment]
'update all' updated figs, limps and armids

**Comment by RogerHuba** [comment]
'update warps' updated fighters

**Comment by RogerHuba** [comment]
Update fixed.

**Comment by DMC73120** [comment]
Re-opening thia for a sumular issue:

![image](https://user-images.githubusercontent.com/74340253/212589050-0fe65974-d4b6-488c-b69b-e4cf2e5b2ea0.png)
reported by flip

these values are always zero, even if you have explored some and have a CIM.

**Comment by RogerHuba** [comment]
Grid fixed.  Closing again.
