### ISSUE TITLE
Max always upgrades Everything.

### ISSUE THREAD

**Issue by DMC73120** [TW2002/mombot#3]
"max f" also upgrades Organics and Equipment, If you have cash, I did not below.

![image](https://user-images.githubusercontent.com/74340253/208289359-9ac9870c-15a3-4f3a-b544-270d3ef0a1a3.png)

**Comment by RogerHuba** [comment]
Confirmed that Max will only upgrade what you tell it to.  
max f - only upgraded fuel (to the max)
max o - only upgraded organics
max e - only upgraded equipment
max o e - Upgraded organics and equipment
max f o - upgraded fuel and organics
max f o e - upgraded all 3
