### ISSUE TITLE
Neg hangs if Ephaggle is in normal mode.

### ISSUE THREAD

**Issue by DMC73120** [TW2002/mombot#4]
Neg will stop and wait for Ephaggle to negotiate if Ephaggle is in normal mode, and EPhaggle will not respond either.

This also effects other commands that use NEG, i.e salesman and merch.

**Comment by DMC73120** [comment]
Correction, these commands do not work at all weather ephaggle is stopped, normal mode, or planet mode.

This problem also effects SDT.

**Comment by RogerHuba** [comment]
Fixed.
