### ISSUE TITLE
Ephaggle loads, even when it is NOT in the startup folder.

### ISSUE THREAD

**Issue by DMC73120** [TW2002/mombot#8]
This is mailnly an issue because SDT will not use internal haggle when Ephaggle is running.

**Comment by daynez** [comment]
For some reason MD deliberately made mombot load ephaggle.  i don't remember why, but it is completely separate from the section that loads the scripts in the startups directory.

**Comment by daynez** [comment]
This appears to be a duplicate with #25

**Comment by RogerHuba** [comment]
Issue fixed.
