### ISSUE TITLE
Deployed Bot in TWX in mombot4 folder

### ISSUE THREAD

**Issue by RogerHuba** [TW2002/mombot#9]
Writing of help files is absolute path looking for mombot.  Need to make more relative.

**Comment by daynez** [comment]
I think this was done deliberately by MD.  At least for a while he was not happy with the bot switching idea and wanted to only support whatever was the current version of mombot.

**Comment by stevenruzicka** [comment]
Yeah, I did change the new bots to just use mombot instead of different versions.  It was just confusing everyone and was encouraging people to use old bots rather than just move to the newest, which was making development more difficult and also support.

**Comment by RogerHuba** [comment]
Intentional.  Closing.
